### ISSUE TITLE
Issue when running gulp command

### ISSUE THREAD

**Issue by jpiemeisl** [niallobrien/generator-gulp-foundation#12]
Having difficulty with the build, here's the error I'm getting:
```
util.js:634
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:634:43)
    at Object.<anonymous> (/Users/me/ProjectDirectory/node_modules/browser-sync/node_modules/http-proxy/lib/http-proxy/index.js:111:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/me/ProjectDirectory/node_modules/browser-sync/node_modules/http-proxy/lib/http-proxy.js:4:17)
    at Module._compile (module.js:460:26)

```

This happens when running the gulp command on a fresh install.

**Comment by sdibella** [comment]
I'm getting the same error with both node v0.12.0 and v0.10.38

**Comment by niallobrien** [comment]
Sorry, but I haven't used this generator in a very long time. Modules update and over time things are bound to break. Ideally I should have shrink-wrapped the dependencies. If you guys resolve any issue, could you please submit a pull-request? Thanks in advance.
