### ISSUE TITLE
`gulp watch` broken

### ISSUE THREAD

**Issue by myrtleTree33** [niallobrien/generator-gulp-foundation#17]
Executing the task `gulp watch` yields an error.

```
/home/joel/repos/test-sass/node_modules/opn/index.js:7
		throw new Error('Expected a `target`');
		      ^
Error: Expected a `target`
    at module.exports (/home/joel/repos/test-sass/node_modules/opn/index.js:7:9)
    at null.cb (/home/joel/repos/test-sass/gulpfile.js:91:23)
    at /home/joel/repos/test-sass/node_modules/browser-sync/lib/browser-sync.js:278:12
    at /home/joel/repos/test-sass/node_modules/browser-sync/node_modules/async-each-series/index.js:15:40
    at executeTask (/home/joel/repos/test-sass/node_modules/browser-sync/lib/browser-sync.js:170:13)
    at Object.module.exports.initUserPlugins [as fn] (/home/joel/repos/test-sass/node_modules/browser-sync/lib/async.js:316:9)
    at /home/joel/repos/test-sass/node_modules/browser-sync/lib/browser-sync.js:149:14
    at iterate (/home/joel/repos/test-sass/node_modules/browser-sync/node_modules/async-each-series/index.js:8:5)
    at /home/joel/repos/test-sass/node_modules/browser-sync/node_modules/async-each-series/index.js:16:16
    at executeTask (/home/joel/repos/test-sass/node_modules/browser-sync/lib/browser-sync.js:170:13)
```

**Comment by stevesioli** [comment]
This issue can be resolved by following the steps for issue #16.
