### ISSUE TITLE
Gulp serve error

### ISSUE THREAD

**Issue by 7xrobin** [niallobrien/generator-gulp-foundation#19]
When I tried execute gulp serve, in begin of project, shows this error:

TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:556:43)
    at Object.<anonymous> (/home/robin/Deleites/node_modules/browser-sync/node_modules/http-proxy/lib/http-proxy/index.js:111:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/robin/Deleites/node_modules/browser-sync/node_modules/http-proxy/lib/http-proxy.js:4:17)
    at Module._compile (module.js:456:26)

**Comment by samvloeberghs** [comment]
+1, no time to look into it tough

**Comment by niallobrien** [comment]
I'm sorry I can't help guys, I really don't use this setup any more.
